apiVersion: v1
kind: Pod
metadata:
  name: fastapi-resources-pod
  labels:
    app: fastapi
    version: v6
spec:
  containers:
  - name: fastapi
    image: karimbk/fastapi-users:v4
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8000
      name: http
    
    # Load secrets as environment variables
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: fastapi-secrets
          key: API_KEY
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: fastapi-secrets
          key: DB_PASSWORD
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: fastapi-secrets
          key: JWT_SECRET
    # Resource requests and limits
    resources:
      requests:
        memory: "128Mi"
        cpu: "128m"
      limits:
        memory: "256Mi"
        cpu: "512m"

